[package]
name = "advent"
version = "0.1.0"
authors = ["Sam Wlody <sawlody@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"